name: "Crowded Counter"
description: "Lab HCM Computer Vision Extension for Crowded Counter Based on IP Camera RTSP"
version: "2.0"
slug: "crowded_counter"
init: false
# url: https://github.com/aguspray001/home-assistant-stream-agent
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
environment:
  URI_CAM: 'rtsp://admin:l4bhcmlt9@192.168.9.250:8554/Streaming/Channels/101'
options:
  uri_cam: 'rtsp://admin:l4bhcmlt9@192.168.9.250:8554/Streaming/Channels/101'
schema:
  uri_cam: str?